"""
Budget planner routes — user-choice flow.

POST /api/budget/options   → returns hotel_options + transport_options (LLM-generated)
POST /api/budget/estimate  → returns cost estimate for user-selected options
"""

import asyncio
import sys
from pathlib import Path

# Allow imports from backend root
sys.path.insert(0, str(Path(__file__).parent.parent))

from fastapi import APIRouter, HTTPException

from budget_engine import calculate_estimated_cost, get_hotel_options, get_transport_options
from schemas import BudgetOptionsResponse, BudgetRequest, EstimateRequest, EstimatedCostResponse

router = APIRouter()


@router.post(
    "/options",
    response_model=BudgetOptionsResponse,
    summary="Get hotel & transport options for user selection",
)
async def get_budget_options(req: BudgetRequest):
    """
    Returns 4 hotel options and 3-4 transport options generated by the LLM
    matching the user's budget tier (low/medium/high).

    All prices are in PKR. Activities and food are not included.
    """
    try:
        hotel_options, transport_options = await asyncio.gather(
            get_hotel_options(
                req.destination, req.num_days, req.num_travelers, req.budget_tier
            ),
            get_transport_options(
                req.destination, req.num_travelers, req.budget_tier
            ),
        )
    except RuntimeError as exc:
        raise HTTPException(status_code=503, detail=str(exc))
    except Exception as exc:
        raise HTTPException(status_code=500, detail=f"Failed to generate options: {exc}")

    return BudgetOptionsResponse(
        hotel_options=hotel_options,
        transport_options=transport_options,
    )


@router.post(
    "/estimate",
    response_model=EstimatedCostResponse,
    summary="Get cost estimate for selected hotel & transport",
)
async def get_budget_estimate(req: EstimateRequest):
    """
    Accepts the original budget_request plus the indices the user selected from the
    /options response. Re-generates the same options (LLM uses temperature=0 for
    consistency) and returns the cost breakdown for the chosen hotel + transport.

    Note: Activities and food are not included in the estimate.
    """
    try:
        hotel_options, transport_options = await asyncio.gather(
            get_hotel_options(
                req.budget_request.destination,
                req.budget_request.num_days,
                req.budget_request.num_travelers,
                req.budget_request.budget_tier,
            ),
            get_transport_options(
                req.budget_request.destination,
                req.budget_request.num_travelers,
                req.budget_request.budget_tier,
            ),
        )
    except RuntimeError as exc:
        raise HTTPException(status_code=503, detail=str(exc))
    except Exception as exc:
        raise HTTPException(status_code=500, detail=f"Failed to generate options: {exc}")

    if req.selected_hotel_index >= len(hotel_options):
        raise HTTPException(
            status_code=400,
            detail=f"selected_hotel_index {req.selected_hotel_index} is out of range "
                   f"(0–{len(hotel_options) - 1})",
        )
    if req.selected_transport_index >= len(transport_options):
        raise HTTPException(
            status_code=400,
            detail=f"selected_transport_index {req.selected_transport_index} is out of range "
                   f"(0–{len(transport_options) - 1})",
        )

    hotel = hotel_options[req.selected_hotel_index]
    transport = transport_options[req.selected_transport_index]

    return calculate_estimated_cost(
        hotel=hotel,
        transport=transport,
        num_days=req.budget_request.num_days,
        num_travelers=req.budget_request.num_travelers,
    )
