export const theme = {
  colors: {
    // Pakistan-first green palette
    primary: '#01411C',
    primaryLight: '#1A6B3C',
    primaryLighter: '#2E8B4A',
    primaryDark: '#002E0F',
    secondary: '#D4AF37',       // Gold accent
    background: '#F8F9FA',      // Light gray for app screens
    surface: '#FFFFFF',         // White for cards
    surfaceSecondary: '#F0F4F2',// Soft green-tinted surface
    textPrimary: '#1A1A1A',
    textSecondary: '#6B7B6E',
    textLight: 'rgba(255,255,255,0.85)',
    textLighter: 'rgba(255,255,255,0.6)',
    error: '#C62828',
    errorLight: '#FFEBEE',
    success: '#2E7D32',
    successLight: '#E8F5E9',
    warning: '#F57C00',
    warningLight: '#FFF3E0',
    border: '#E0E7E3',
    borderFocused: '#01411C',
    link: '#01411C',
    gold: '#D4AF37',
    goldLight: '#F5E6A3',
    cream: '#FDF8F0',
    white: '#FFFFFF',
    black: '#000000',
    overlay: 'rgba(0,0,0,0.5)',
    heroOverlay: 'rgba(1,65,28,0.92)',
  },
  typography: {
    heading: 'System',
    body: 'System',
  },
  fontSize: {
    xs: 11,
    sm: 13,
    md: 15,
    base: 16,
    lg: 17,
    xl: 20,
    xxl: 24,
    xxxl: 32,
    display: 40,
  },
  fontWeight: {
    regular: '400' as const,
    medium: '500' as const,
    semibold: '600' as const,
    bold: '700' as const,
    extrabold: '800' as const,
  },
  spacing: {
    xs: 4,
    sm: 8,
    md: 16,
    lg: 24,
    xl: 32,
    xxl: 48,
  },
  borderRadius: {
    sm: 6,
    md: 10,
    lg: 16,
    xl: 24,
    xxl: 32,
    full: 999,
  },
  shadows: {
    sm: {
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 0.06,
      shadowRadius: 4,
      elevation: 2,
    },
    md: {
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.10,
      shadowRadius: 8,
      elevation: 4,
    },
    lg: {
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.15,
      shadowRadius: 16,
      elevation: 8,
    },
    xl: {
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 8 },
      shadowOpacity: 0.20,
      shadowRadius: 24,
      elevation: 12,
    },
  },
};
